### ISSUE TITLE
Running float/rationalize_spec separately fails

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#1218]
Running the full test spec works fine, but when running the folder `spec/core/float` or running this test separately, the `rationalize` method cannot be found.

```
$ bin/natalie spec/core/float/rationalize_spec.rb
EEEFFF

Failed specs:
Float#rationalize
  raises a FloatDomainError for Infinity
    #<Proc:0x557b2bbc9220> should have raised FloatDomainError, but instead raised #<NoMethodError: undefined method `rationalize' for Infinity:Float>
    (spec/core/float/rationalize_spec.rb:34:in `block in block in block')
Float#rationalize
  raises a FloatDomainError for NaN
    #<Proc:0x557b2bbcae20> should have raised FloatDomainError, but instead raised #<NoMethodError: undefined method `rationalize' for NaN:Float>
    (spec/core/float/rationalize_spec.rb:38:in `block in block in block')
Float#rationalize
  raises ArgumentError when passed more than one argument
    #<Proc:0x557b2bbcc8a0> should have raised ArgumentError, but instead raised #<NoMethodError: undefined method `rationalize' for 0.3:Float>
    (spec/core/float/rationalize_spec.rb:42:in `block in block in block')
Float#rationalize
  returns self as a simplified Rational with no argument
    undefined method `rationalize' for 3382729202.92822:Float (NoMethodError)
      spec/core/float/rationalize_spec.rb:7:in `block in block in block'
      /home/herwin/code/natalie/test/support/spec.rb:1426:in `call'
      /home/herwin/code/natalie/test/support/spec.rb:1426:in `block in run_specs'
      /home/herwin/code/natalie/test/support/spec.rb:1405:in `each'
      /home/herwin/code/natalie/test/support/spec.rb:1405:in `run_specs'
      /home/herwin/code/natalie/test/support/spec.rb:1458:in `block in block'
      spec/core/float/rationalize_spec.rb:5:in `<main>'
Float#rationalize
  simplifies self to the degree specified by a Rational argument
    undefined method `rationalize' for 0.3:Float (NoMethodError)
      spec/core/float/rationalize_spec.rb:14:in `block in block in block'
      /home/herwin/code/natalie/test/support/spec.rb:1426:in `call'
      /home/herwin/code/natalie/test/support/spec.rb:1426:in `block in run_specs'
      /home/herwin/code/natalie/test/support/spec.rb:1405:in `each'
      /home/herwin/code/natalie/test/support/spec.rb:1405:in `run_specs'
      /home/herwin/code/natalie/test/support/spec.rb:1458:in `block in block'
      spec/core/float/rationalize_spec.rb:5:in `<main>'
Float#rationalize
  simplifies self to the degree specified by a Float argument
    undefined method `rationalize' for 0.3:Float (NoMethodError)
      spec/core/float/rationalize_spec.rb:25:in `block in block in block'
      /home/herwin/code/natalie/test/support/spec.rb:1426:in `call'
      /home/herwin/code/natalie/test/support/spec.rb:1426:in `block in run_specs'
      /home/herwin/code/natalie/test/support/spec.rb:1405:in `each'
      /home/herwin/code/natalie/test/support/spec.rb:1405:in `run_specs'
      /home/herwin/code/natalie/test/support/spec.rb:1458:in `block in block'
      spec/core/float/rationalize_spec.rb:5:in `<main>'

0 spec(s) passed.
3 spec(s) failed.
3 spec(s) errored.
```

**Comment by herwinw** [comment]
```ruby
# skip-test
```
Well, that explains something. 

It is a bit confusing that `rake test_folder[spec/core/float]` still runs these disabled specs. I'm kind of tempted to just remove this spec from the repository: we have the overview at https://natalie-lang.org/specs that shows which specs haven't been completed yet, and it's not like we have a complete copy of the specs folders anyway.

**Comment by seven1m** [comment]
Yeah at one point we had imported a bunch of ruby specs and disabled ones that weren't yet working. But I agree there's no need for that, esp. after the practice of NATFIXME was added. We can just remove the two spec files with `skip-test` in them.
