### ISSUE TITLE
Constant cannot be found in parent namespace

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#1409]
Here's a case where we cannot find the module to include:

```ruby
class Foo
  class SameName
  end
end

class Bar < Foo
  module Baz
  end

  class SameName
    include Baz
  end
end
```

output:

```
Traceback (most recent call last):
        3: from wat.rb:6:in `<main>'
        2: from wat.rb:10:in `<class:Bar>'
        1: from wat.rb:11:in `<class:SameName>'
wat.rb:11:in `const_missing': uninitialized constant Foo::SameName::Baz (NameError)
```

Natalie gets confused by the original ownership of `Foo::SameName`. Maybe because we are reopening the class?

If you rename the `Foo::SameName` up top to something else, then the `Baz` module can be found.

**Comment by seven1m** [comment]
Ahhh, I think this is the actual issue:

```
class Foo
  class SameName
  end
end

class Bar < Foo
  class SameName
  end
end

p Foo::SameName == Bar::SameName # => false in MRI
```

This prints `true` with Natalie. Fun!
