### ISSUE TITLE
Code generator error for break in case in loop

### ISSUE THREAD

**Issue by herwinw** [natalie-lang/natalie#1536]
I admit, an example is much clearer than this title:
```ruby
i = 0
while true
  case i
  when 0
    i += 1
    puts "In loop: #{i}"
  else
    break
  end
end
puts "After: #{i}"
```
This prints the expected output in MRI:
```
In loop: 0
After: 1
```
But compilation in Natalie breaks:
```
lib/natalie/compiler/instructions/if_instruction.rb:43:in `block in generate': branch sizes uneven! 1 != 0 (RuntimeError)
	from lib/natalie/compiler/backends/cpp_backend/transform.rb:141:in `normalize_stack'
	from lib/natalie/compiler/instructions/if_instruction.rb:29:in `generate'
	from lib/natalie/compiler/backends/cpp_backend/transform.rb:32:in `block in transform'
	from lib/natalie/compiler/instruction_manager.rb:31:in `walk'
	from lib/natalie/compiler/backends/cpp_backend/transform.rb:30:in `transform'
	from lib/natalie/compiler/instructions/while_instruction.rb:57:in `block in generate'
	from lib/natalie/compiler/backends/cpp_backend/transform.rb:132:in `with_same_scope'
	from lib/natalie/compiler/instructions/while_instruction.rb:54:in `generate'
	from lib/natalie/compiler/backends/cpp_backend/transform.rb:32:in `block in transform'
	from lib/natalie/compiler/instruction_manager.rb:31:in `walk'
	from lib/natalie/compiler/backends/cpp_backend/transform.rb:30:in `transform'
	from lib/natalie/compiler/backends/cpp_backend.rb:131:in `transform_instructions'
	from lib/natalie/compiler/backends/cpp_backend.rb:118:in `generate'
	from lib/natalie/compiler/backends/cpp_backend.rb:103:in `write_file'
	from lib/natalie/compiler/backends/cpp_backend.rb:96:in `write_file_for_debugging'
	from lib/natalie/compiler.rb:48:in `write_file_for_debugging'
	from bin/natalie:156:in `run'
	from bin/natalie:324:in `<main>'
```

**Comment by herwinw** [comment]
https://github.com/ruby/net-protocol/blob/master/lib/net/protocol.rb#L46-L50

I encountered this issue while trying to add the `net` gem.
