### ISSUE TITLE
natalie-lang.org server.rb doesn't work with latest Natalie

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#2095]
Starting in 2ef5771069b8de5f145952612648e0ff27d0bc99 the payload returned from https://natalie-lang.org/stats/stats.json is truncated. Need to investigate...

**Comment by seven1m** [comment]
Also, 9 out of 10 of the child processes see the following error for every socket connection:

```
["Errno::EAGAIN", "Resource temporarily unavailable", ["server.rb:41:in `accept'", "server.rb:41:in `block in block in block in block'", "server.rb:40:in `loop'", "server.rb:40:in `block in block in block'", "server.rb:39:in `fork'", "server.rb:39:in `block in block'", "src/enumerable.rb:624:in `block in collect'", "src/enumerable.rb:624:in `each'", "src/enumerable.rb:624:in `collect'", "server.rb:38:in `<main>'"]]["Errno::EAGAIN", "Resource temporarily unavailable", ["server.rb:41:in `accept'", "server.rb:41:in `block in block in block in block'", "server.rb:40:in `loop'", "server.rb:40:in `block in block in block'", "server.rb:39:in `fork'", "server.rb:39:in `block in block'", "src/enumerable.rb:624:in `block in collect'", "src/enumerable.rb:624:in `each'", "src/enumerable.rb:624:in `collect'", "server.rb:38:in `<main>'"]]
```

It seems that `server.accept` returns one good connection and raises an error for all the other children waiting.

**Comment by funny-falcon** [comment]
It is well known issue with non-blocking accept from many threads/processes: kernel wakes all `epool/poll/select` waiters of socket, but only one succeed.

Nginx works around by using cross-process lock around waiting for accept. Some other servers use blocking listen socket and do accept in separate threads (iirc, Rainbow did it).

**Comment by seven1m** [comment]
Interestingly, Firefox and `curl` were both getting the whole response, but Chrome was not. I suspect it's in how the client reads the data off the socket, causing some combination of a partial write and/or EAGAIN, which we are not handling as we should. Fixed in #2488.
