### ISSUE TITLE
Kernel.exit! bug

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#2323]
Saw this in CI, I assume it's due to something flaky with our threads:

```
Kernel.exit!
  exits when called from a thread
    Expected exit status 21 but actual is 1
    (/natalie/spec/shared/process/exit.rb:91:in `block in block in block')

27 spec(s) passed.
1 spec(s) failed.
0 spec(s) errored.
6 spec(s) skipped.
 FAIL ruby/spec::spec/core/kernel/exit_spec.rb#test_0001_passes all specs (1925.68s)
        Expected #<Process::Status: pid 14366 exit 1> to be success?.
        /natalie/test/ruby/ruby_specs_test.rb:35:in `block (4 levels) in <top (required)>'
```

**Comment by seven1m** [comment]
I'm able to reproduce a segfault by running this repeatedly while heavily loading all my CPUs:

<img width="1624" alt="Screenshot 2024-11-14 at 8 19 52 AM" src="https://github.com/user-attachments/assets/d5b3f2e1-4307-4f31-a4a5-7a274360684e">
