### ISSUE TITLE
Error in yaml_emitter_emit

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#2440]
1. Apply the following diff (commit fcbbf23974e10cd16e62f79efd259997f6b6786c)

  ```diff
--- a/test/support/formatters/yaml_formatter.rb
+++ b/test/support/formatters/yaml_formatter.rb
@@ -1,3 +1,5 @@
+require 'yaml'
+
 class YamlFormatter
   def print_context(*) ; end

@@ -10,20 +12,20 @@ def print_failure(*); end
   def print_skipped(*); end

   def print_finish(test_count, failures, errors, skipped)
-    print "---\n"
+    struct = {
+      'examples' => test_count,
+      'failures' => failures.size,
+      'errors' =>  errors.size,
+    }
     if failures.any? || errors.any?
-      print "exceptions:\n"
-      (errors + failures).each do |failure|
+      outcomes = (errors + failures).map do |failure|
         context, test, error = failure
         outcome = error.is_a?(SpecFailedException) ? 'FAILED' : 'ERROR'
         str = "#{test} #{outcome}\n"
         str << error.message << "\n" << error.backtrace.to_s
-        print '- ', str.inspect, "\n"
       end
+      struct['exception'] = outcomes
     end
-
-    print 'examples: ', test_count, "\n"
-    print 'failures: ', failures.size, "\n"
-    print 'errors: ', errors.size, "\n"
+    print struct.to_yaml
   end
```

2. Refresh `spec/language/method_spec.rb` from ruby/spec

3. Run:

  ```sh
  bin/natalie spec/language/method_spec.rb -f yaml
  ```

You get the following error:

```
Traceback (most recent call last):
        5: from spec/language/method_spec.rb:1419:in '<main>'
        4: from /home/tim/pp/natalie/test/support/spec.rb:1700:in 'block in block'
        3: from /home/tim/pp/natalie/test/support/spec.rb:1697:in 'run_specs'
        2: from /home/tim/pp/natalie/test/support/formatters/yaml_formatter.rb:29:in 'print_finish'
        1: from /home/tim/pp/natalie/lib/yaml.rb:23:in 'to_yaml'
/home/tim/pp/natalie/lib/yaml.rb:23:in 'dump': Error in yaml_emitter_emit (RuntimeError)
```

**Comment by seven1m** [comment]
Possibly related to #1839 which I just closed.

**Comment by herwinw** [comment]
To speed up the reproduction, replace the two yaml-lines in the diff with `require 'pp'` and `pp struct`, and make a seperate file with `struct = <copy-paste output>; print struct.to_yaml`.

It looks like it has issues with long arrays with long lines, after removing a certain number of lines in this test script, it prints the output again.

**Comment by seven1m** [comment]
Here's the smallest reproduction I could get:

```ruby
require 'yaml'
puts({
  "foo" => ["x" * 750] * 22
}.to_yaml)
```

**Comment by seven1m** [comment]
Wait, even better! 🎉 

```ruby
require 'yaml'
puts ("x" * 17000).to_yaml
```
