### ISSUE TITLE
Get ChunkyPNG README example working

### ISSUE THREAD

**Issue by seven1m** [natalie-lang/natalie#867]
I'd like to get this code from the ChunkyPNG readme working:

```ruby
require 'chunky_png'

# Creating an image from scratch, save as an interlaced PNG
png = ChunkyPNG::Image.new(16, 16, ChunkyPNG::Color::TRANSPARENT)
png[1,1] = ChunkyPNG::Color.rgba(10, 20, 30, 128)
png[2,1] = ChunkyPNG::Color('black @ 0.5')
png.save('filename.png', :interlace => true)
```

Here are my steps to test:

1. Clone the repo:

   ```sh
   git clone https://github.com/wvanbergen/chunky_png
   cd chunky_png
   ```

2. Save the above code snippet as a file `example.rb` in the directory.

3. Run the example code:

   ```sh
   ../natalie/bin/natalie -I lib example.rb
   ```

4. Observe any errors and fix! Rinse, repeat...

**Comment by nanobowers** [comment]
Assuming #1041 is agreeable and works, it appears the next thing that is failing is `crc32` from Zlib:
```
22:18 $ ../natalie/bin/natalie -I lib example.rb
Traceback (most recent call last):
        9: from example.rb:7:in `<main>'
        8: from lib/chunky_png/canvas/png_encoding.rb:43:in `save'
        7: from lib/chunky_png/canvas/png_encoding.rb:43:in `open'
        6: from lib/chunky_png/canvas/png_encoding.rb:43:in `block in save'
        5: from lib/chunky_png/canvas/png_encoding.rb:35:in `write'
        4: from lib/chunky_png/datastream.rb:165:in `write'
        3: from lib/chunky_png/datastream.rb:125:in `each_chunk'
        2: from lib/chunky_png/datastream.rb:165:in `block in write'
        1: from lib/chunky_png/chunk.rb:89:in `write'
lib/chunky_png/chunk.rb:80:in `write_with_crc': undefined method `crc32' for Zlib:Module (NoMethodError)
```

**Comment by nanobowers** [comment]
@seven1m I think the example is working now, or at least it executes successfully.

```
08:38 $ ../natalie/bin/natalie -I lib example.rb
08:38 $ ls -lt *.png
-rw-r--r-- 1 nanobowers nanobowers 160 Mar 11 08:38 filename.png
```

**Comment by seven1m** [comment]
Whoa cool!!!!!!! I get the same image with both MRI and with Natalie. 🎉
